### ISSUE TITLE
Issue when syncing rom manifest

### ISSUE THREAD

**Issue by linusrg1** [DerpFest-11/manifest#10]
Linus Guglielmo, [30.10.21 17:29]
Checking out: 63% (544/863) AOSiP/platform_prebuilts_clang_host_linux-x86error: Cannot checkout vendor_gms: ManifestInvalidRevisionError: revision 11 in vendor_gms not found
Checking out:  63% (544/863), done in 47m38.309s
error: in sync -j10 --force-sync: revision 11 in vendor_gms not found

Is there a way to solve this error?

**Comment by NurKeinNeid** [comment]
what about repo init?

**Comment by linusrg1** [comment]
I did repo init -u "repo url here" -b 11

**Comment by NurKeinNeid** [comment]
but there is no vendor_gms in manifest

**Comment by linusrg1** [comment]
this is what I follow to sync all my roms. Maybe I should just use ur commands instead? https://amygrace.dev/2021/05/08/build-roms-pt2.html

**Comment by linusrg1** [comment]
> but there is no vendor_gms in manifest

Idk what this means as I have never encountered it before so idk how to solve it tbh.

**Comment by linusrg1** [comment]
> what about repo init?

sry for not listening to u properly I am very tired lol,.

**Comment by NurKeinNeid** [comment]
No worries, I can understand

**Comment by linusrg1** [comment]
> No worries, I can understand
after running just straight "repo init" should I then run I did repo init -u "repo url here" -b 11

and does your rom just not use  vendor_gms (I have no idea what that error really means)

**Comment by NurKeinNeid** [comment]
its old_vendor_gms in manifest

**Comment by linusrg1** [comment]
> its old_vendor_gms in manifest

so what should I modify with my command to rectify it? Sorry if I am not getting this.

**Comment by NurKeinNeid** [comment]
just do

repo init -u git://github.com/DerpFest-11/manifest.git -b 11

and force sync

**Comment by linusrg1** [comment]
sorry bout that can't believe I didn't notice that small change thanks!
