### ISSUE TITLE
why

### ISSUE THREAD

**Issue by ghost** [DerpFest-11/manifest#5]
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:599:22: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
    if (mode.flags & DRM_MODE_FLAG_CMD_MODE_PANEL) {
                     ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:734:28: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
  if (current_mode.flags & DRM_MODE_FLAG_CMD_MODE_PANEL) {
                           ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:737:28: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
  if (current_mode.flags & DRM_MODE_FLAG_VID_MODE_PANEL) {
                           ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:853:22: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
  if (to_set.flags & DRM_MODE_FLAG_CMD_MODE_PANEL) {
                     ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:854:17: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
    mode_flag = DRM_MODE_FLAG_CMD_MODE_PANEL;
                ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:855:24: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
    switch_mode_flag = DRM_MODE_FLAG_VID_MODE_PANEL;
                       ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:856:29: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
  } else if (to_set.flags & DRM_MODE_FLAG_VID_MODE_PANEL) {
                            ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:857:17: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
    mode_flag = DRM_MODE_FLAG_VID_MODE_PANEL;
                ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:858:24: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
    switch_mode_flag = DRM_MODE_FLAG_CMD_MODE_PANEL;
                       ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:861:28: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
  if (current_mode.flags & DRM_MODE_FLAG_CMD_MODE_PANEL) {
                           ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:862:22: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
    curr_mode_flag = DRM_MODE_FLAG_CMD_MODE_PANEL;
                     ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:863:35: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
  } else if (current_mode.flags & DRM_MODE_FLAG_VID_MODE_PANEL) {
                                  ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:864:22: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
    curr_mode_flag = DRM_MODE_FLAG_VID_MODE_PANEL;
                     ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:915:21: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
    if (mode_flag & DRM_MODE_FLAG_VID_MODE_PANEL) {
                    ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:945:52: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
        (connector_info_.modes[index].mode.flags & DRM_MODE_FLAG_VID_MODE_PANEL) ?
                                                   ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:1282:29: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
  if (panel_mode_changed_ & DRM_MODE_FLAG_VID_MODE_PANEL) {
                            ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:1564:30: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
   if (panel_mode_changed_ & DRM_MODE_FLAG_CMD_MODE_PANEL) {
                             ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:1567:36: error: use of undeclared identifier 'DRM_MODE_FLAG_VID_MODE_PANEL'
  } else if (panel_mode_changed_ & DRM_MODE_FLAG_VID_MODE_PANEL) {
                                   ^
hardware/qcom-caf/sm8150/display/sdm/libs/core/drm/hw_device_drm.cpp:1786:17: error: use of undeclared identifier 'DRM_MODE_FLAG_CMD_MODE_PANEL'
    mode_flag = DRM_MODE_FLAG_CMD_MODE_PANEL;
                ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by NurKeinNeid** [comment]
I have no fucking clue

**Comment by moditjain9777** [comment]
is this issue resolved?
